name: Update GitHub Language Stats

on:
  schedule:
    - cron: '0 */24 * * *' # Run every 24 hours
  workflow_dispatch:       # Allow manual trigger
  
permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Fetch stats from gitpeek-lang
        run: |
          mkdir -p assets
          curl "https://gitpeek-lang.onrender.com/api/GitHubStats/eerieA/graph?barHeight=15&lgItemWidth=145&lgItemMaxCnt=8" > assets/github-language-stats.svg

      - name: Commit and push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/github-language-stats.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update GitHub language stats"
          git push
