name: Update GitHub Language Stats

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:       # Allow manual trigger
  
permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Fetch stats from gitpeek-lang
        run: |
          curl "https://gitpeek-lang.onrender.com/api/GitHubStats/eerieA/graph?barHeight=15&lgItemWidth=145&lgItemMaxCnt=8" > github-language-stats.svg
      
      - name: Commit and push if changed
        run: |
          git config user.name eeriea
          git config user.email ninja.duan@gmail.com
          git add github-language-stats.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update GitHub language stats"
          git push
